---

- hosts: gcp
  sudo: yes

  tasks:
  - name: Ensure NIP is installed.
    apt: 
      name=ntp
      state=installed

  - name: Ensure NTP is installed.
    service: 
      name=ntp
      state=started
      enabled=yes

  - name: Install Java
    apt:
      name=default-jre
      state=present

  - name: Jenkins package
#    command: bash -c " touch 1"
#    command: echo '#!/bin/bash' >> 1
    command: bash -c "wget -q -O - https://pkg.jenkins.io/debian/jenkins-ci.org.key | apt-key add -"
    command: bash -c "echo deb https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list"
    become: true
#    force: yes

#  - name: Inst deb package
#    apt:
#      deb: https://pkg.jenkins.io/debian-stable binary/

  - name: Update
    apt:
      update_cache: yes

  - name: Install Jenkins
    apt:
      name: jenkins
      state: present
      force: yes
    
  - name: Install apache2
    apt:
      name: apache2
      state: latest

  - name: Install ufw
    apt:
      name: ufw
      state: latest
      force: yes

  - name: Launching firewall
    ufw:
      state: enabled
      rule: allow
      port: 8080
      name: OpenSSH

  - name: Enabling 8080
    ufw:
      rule: allow
      port: 8080

  - name: Enable HTTP
    ufw:
      rule: allow
      port: 80
